### ISSUE TITLE
Manual unpack .dll/.so

### ISSUE THREAD

**Issue by gravit0** [JnCrMx/discord-game-sdk4j#18]
Hey. Can I manual unpack jni .dll/.so library without reflection? I using following code:
```
		System.load(pathToDiscordSdkLib.toAbsolutePath().toString());
		System.load(pathToLib.toAbsolutePath().toString());
        try {
            Method method = Core.class.getDeclaredMethod("initDiscordNative", String.class);
            method.setAccessible(true);
            method.invoke(null, pathToDiscordSdkLib.toAbsolutePath().toString());
        } catch (NoSuchMethodException | IllegalAccessException | InvocationTargetException e) {
            throw new RuntimeException(e);
        }
```
My code unpack dll and so to custom location and check checksum. Using `Core.init` currently not possible.

**Comment by JnCrMx** [comment]
Hmmm, so it would be sufficient to make the ``initDiscordNative`` method public and add some documentation to it?

**Comment by gravit0** [comment]
Yes. You can also create a method "Core.init(pathToDiscordJniLib, pathToDiscordSdkLib)" if the initialization method is changed
It also eliminates the need for a library "nativeutils"

**Comment by JnCrMx** [comment]
Would ``Core.init(pathToDiscordJniLib, pathToDiscordSdkLib)`` also perform the ``System.load(...)`` operation?
I'm asking, because I'm not sure if it wouldn't be better to let the application load the library itself (so you could choose between ``System.load`` for absolute paths and ``System.loadLibrary`` for searching in the system library path).

Also, I'm not sure about dropping nativeutils. It would be very welcome for licensing reasons (even though it shouldn't be a huge problem anyway, as it's also MIT licensed). On the other hand, removing the ``Core.init(File discordLibrary)`` method entirely would break compatibility to old code.

Maybe, I could keep the method, but write my own code to extract the native library, so you can still choose between letting the library automatically extract natives or extracting them yourself.

**Comment by gravit0** [comment]
For the sake of being able to use System.loadLibrary, it is really better to open the `initDiscordNative` method, or make another `Core.init()` method. This will allow you to choose a convenient way to load native libraries.
