### ISSUE TITLE
`FileNotFoundException` with Java 22 (java-impl branch)

### ISSUE THREAD

**Issue by Desoroxxx** [JnCrMx/discord-game-sdk4j#79]
Updated my project to Java 22, launched my game and https://mclo.gs/IxPgr6c then I went back to Java 21 and it worked again, so it seems this is incompatible with Java 21 as is.

**Comment by Desoroxxx** [comment]
From answers that I got on a Java Discord and testing, it seems that simply changing for example `\\\\?\\pipe\\discord-ipc-0` to `\\\\.\\pipe\\discord-ipc-0` should work.
`?` apparently worked by accident

**Comment by JnCrMx** [comment]
This seems to be correct, at least according to the [Microsoft documentation](https://learn.microsoft.com/en-us/windows/win32/ipc/pipe-names).

 @letorbi Do you have any thoughts on this? I am no expert on the Windows side of things, sadly...

**Comment by letorbi** [comment]
I am also more a Linux user that a Windows expert, but `\\\\?\\pipe` actually seems to be a mistake. As stated in my related PR #61, I just copied the path from the Rust discord-sdk project...

I don't know why Rust discord-sdk uses `?` instead of `.`, but if the latter works with Java 22 and Java 21 and is also the proper way to access a pipe, I guess we should change our path to `\\\\.\\pipe\\discord-ipc-0`.

**Comment by Desoroxxx** [comment]
I forgot to mention since my last comment I tried creating a `RandomAccessFile` with `?` in my own project wich lead to a FNF on J22 I then tried with `.` and that worked no FNF was thrown. So from my testing it seems that it would work

**Comment by Desoroxxx** [comment]
Do you want me to create a PR for this? This is the only thing preventing me migrating to J22 😅

**Comment by letorbi** [comment]
I think @immails has already created #81 to fix this issue.

**Comment by cedricwiesel** [comment]
Hey there @JnCrMx,
Is there any chance the fix from the above mentioned PR could be implemented anytime soon? I am currently using this library for a project at uni and am experiencing the error. I cannot edit the library locally since I am forced to import any used libraries via gradle so I am very reliant on this getting fixed. Thanks in advance!

**Comment by letorbi** [comment]
@cedricwiesel For the meantime you could use JitPack to import @immails master branch, which contains the fix, into you project. See https://jitpack.io/#immails/discord-game-sdk4j/master-SNAPSHOT for details.

**Comment by JnCrMx** [comment]
I merged #81 and I hope this issue is fixed now ^^

If there's any more problems related to this, feel free to comment and I'll reopen the issue.
